### ISSUE TITLE
Improved Front-end Styles on gh-pages Branch

### ISSUE THREAD

**Issue by jchck** [gregburton/last-week#4]
Not wanting to step on anyone's toes here but would there be any opposition to improved styles (CSSing) on the gh-page?

**Comment by gregburton** [comment]
No opposition here. Glad you want to contribute! BTW I just cleaned up the gh-pages branch, and set up the .git/config so gh-pages now mirrors the master branch.

**Comment by gregburton** [comment]
I'm also planning on adding in some jQuery pagination

**Comment by noahhh** [comment]
I would not complain.

**Comment by jaechick** [comment]
Awesome, sweetness.

**Comment by gregburton** [comment]
^^ sorry not sorry: https://www.youtube.com/watch?v=ROatPGGMvXg
